"""drop_info_pages

Revision ID: ab3182555235
Revises: 4b7d9e3f1a2c
Create Date: 2026-05-14 16:26:00.444230

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ab3182555235'
down_revision = '4b7d9e3f1a2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('info_pages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_info_pages_slug'))

    op.drop_table('info_pages')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('info_pages',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=300), nullable=False),
    sa.Column('slug', mysql.VARCHAR(length=320), nullable=False),
    sa.Column('content_html', mysql.TEXT(), nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('seo_title', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('seo_description', mysql.VARCHAR(length=400), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mariadb_collate='utf8mb4_uca1400_ai_ci',
    mariadb_default_charset='utf8mb4',
    mariadb_engine='InnoDB'
    )
    with op.batch_alter_table('info_pages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_info_pages_slug'), ['slug'], unique=True)

    # ### end Alembic commands ###
